# Generated by Django 4.2.2 on 2023-06-20 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import driver.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(null=True, upload_to=driver.models.Driver.upload_path)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('driver_category', models.CharField(max_length=255)),
                ('document_code', models.CharField(max_length=255)),
                ('expiry_date', models.DateTimeField()),
                ('photo', models.ImageField(null=True, upload_to=driver.models.Documents.upload_path)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.driver')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('car_modal', models.CharField(max_length=255)),
                ('license_plate_no', models.CharField(max_length=255)),
                ('base_rate', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('car_make', models.CharField(max_length=255)),
                ('car_year', models.IntegerField()),
                ('photo', models.ImageField(null=True, upload_to=driver.models.Car.upload_path)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.driver')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
