# Generated by Django 4.2.2 on 2023-06-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
