# Generated by Django 4.2.2 on 2023-06-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usermaster_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='otp_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
